package com.example.fintech_2024_dombrovskaya.models

import kotlinx.serialization.Serializable

@Serializable
data class Description(
    val kinopoiskId: Int? = 0,
    val kinopoiskHDId: String? = null,
    val imdbId: String? = null,
    val nameRu: String? = null,
    val nameEn: String? = null,
    val nameOriginal: String? = null,
    val posterUrl: String? = null,
    val posterUrlPreview: String? = null,
    val coverUrl: String? = null,
    val logoUrl: String? = null,
    val reviewsCount: Int? = 0,
    val ratingGoodReview: String? = null,
    val ratingGoodReviewVoteCount: Int? = 0,
    val ratingKinopoisk: String? = null,
    val ratingKinopoiskVoteCount: Int? = 0,
    val ratingImdb: String? = null,
    val ratingImdbVoteCount: Int? = 0,
    val ratingFilmCritics: String? = null,
    val ratingFilmCriticsVoteCount: Int? = 0,
    val ratingAwait: Double? = 0.0,
    val ratingAwaitCount: Int? = 0,
    val ratingRfCritics: String? = null,
    val ratingRfCriticsVoteCount: Int? = 0,
    val webUrl: String? = null,
    val year: Int? = 0,
    val filmLength: String? = null,
    val slogan: String? = null,
    val description: String? = null,
    val shortDescription: String? = null,
    val editorAnnotation: String? = null,
    val isTicketsAvailable: Boolean? = null,
    val productionStatus: String? = null,
    val type: String? = null,
    val ratingMpaa: String? = null,
    val ratingAgeLimits: String? = null,
    val countries: List<Country>? = null,
    val genres: List<Genre>? = null,
    val startYear: String? = null,
    val endYear: String? = null,
    val serial: Boolean? = null,
    val shortFilm: Boolean? = null,
    val completed: Boolean? = null,
    val hasImax: Boolean? = null,
    val has3D: Boolean? = null,
    val lastSync: String? = null,
)
